version: '3.8'

services:
  rust-proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile.rust
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=debug
    depends_on:
      - python-server
    volumes:
      - ./Settings.toml:/usr/local/bin/Settings.toml

  python-server:
    build:
      context: .
      dockerfile: docker/Dockerfile.python
    deploy:
      replicas: 2
    expose:
      - "5000" 