[api_gateway]
target_url = "python-server:5000"
proxy_server_addr = "0.0.0.0:3000"


[rate_limiter]
redis_addr = "redis:6379"
ip_whitelist = ["127.0.0.1", "198.0.0.1"]

[[rate_limiter.limiter]]
strategy = "url"
bucket = { tokens_count = 5, add_tokens_every = 10 }

[[rate_limiter.limiter]]
strategy = "ip"
bucket = { tokens_count = 10, add_tokens_every = 120 }

[[rate_limiter.limiter]]
strategy = "auth_header"
bucket = { tokens_count = 3, add_tokens_every = 120 }