FROM rust:latest AS builder

WORKDIR /usr/src/app
COPY . .

RUN cargo build --release

FROM debian:bookworm-slim
COPY --from=builder /usr/src/app/target/release/rate_limiter /usr/local/bin/rate_limiter
COPY Settings.toml /usr/local/bin/

WORKDIR /usr/local/bin
CMD ["rate_limiter"] 